# Generated by Django 2.1.3 on 2019-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='method',
        ),
        migrations.AddField(
            model_name='permission',
            name='method_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='方法类型'),
        ),
    ]
