# Generated by Django 2.1.3 on 2019-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190926_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='手机号'),
        ),
    ]
