# Generated by Django 2.1.3 on 2019-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190929_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roleInfo', to='backend.Role', verbose_name='角色'),
        ),
    ]
