# Generated by Django 2.1.3 on 2019-10-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190929_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='backend.Role', verbose_name='角色'),
        ),
    ]
